language: node_js
node_js:
  - "10"

before_install:
  - scripts/installChrome.sh

script:
  - scripts/printPDF.sh

deploy:
  provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: "files.tylertracy.com"
  skip_cleanup: true
  on:
    branch: master
  local_dir: out
